namespace DOL.WHD.Section14c.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UpdateKeysToGuid : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ApplicationSubmissions", "Employer_Id", "dbo.EmployerInfoes");
            DropForeignKey("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id", "dbo.WorkerCountInfoes");
            DropForeignKey("dbo.EmployerInfoes", "ParentAddress_Id", "dbo.Addresses");
            DropForeignKey("dbo.EmployerInfoes", "PhysicalAddress_Id", "dbo.Addresses");
            DropForeignKey("dbo.SourceEmployers", "Address_Id", "dbo.Addresses");
            DropForeignKey("dbo.WorkSites", "Address_Id", "dbo.Addresses");
            DropForeignKey("dbo.ApplicationSubmissions", "HourlyWageInfo_Id", "dbo.HourlyWageInfoes");
            DropForeignKey("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id", "dbo.PrevailingWageSurveyInfoes");
            DropForeignKey("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes");
            DropForeignKey("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes");
            DropForeignKey("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id", "dbo.PieceRateWageInfoes");
            DropForeignKey("dbo.WIOAWorkers", "WIOA_Id", "dbo.WIOAs");
            DropForeignKey("dbo.ApplicationSubmissions", "WIOA_Id", "dbo.WIOAs");
            DropForeignKey("dbo.Employees", "WorkSite_Id", "dbo.WorkSites");
            DropForeignKey("dbo.WorkSiteWorkSiteType", "WorkSite_Id", "dbo.WorkSites");
            DropIndex("dbo.ApplicationSubmissions", new[] { "Employer_Id" });
            DropIndex("dbo.ApplicationSubmissions", new[] { "HourlyWageInfo_Id" });
            DropIndex("dbo.ApplicationSubmissions", new[] { "PieceRateWageInfo_Id" });
            DropIndex("dbo.ApplicationSubmissions", new[] { "WIOA_Id" });
            DropIndex("dbo.EmployerInfoes", new[] { "NumSubminimalWageWorkers_Id" });
            DropIndex("dbo.EmployerInfoes", new[] { "ParentAddress_Id" });
            DropIndex("dbo.EmployerInfoes", new[] { "PhysicalAddress_Id" });
            DropIndex("dbo.HourlyWageInfoes", new[] { "MostRecentPrevailingWageSurvey_Id" });
            DropIndex("dbo.SourceEmployers", new[] { "Address_Id" });
            DropIndex("dbo.SourceEmployers", new[] { "PrevailingWageSurveyInfo_Id" });
            DropIndex("dbo.PieceRateWageInfoes", new[] { "MostRecentPrevailingWageSurvey_Id" });
            DropIndex("dbo.WIOAWorkers", new[] { "WIOA_Id" });
            DropIndex("dbo.WorkSites", new[] { "Address_Id" });
            DropIndex("dbo.Employees", new[] { "WorkSite_Id" });
            DropIndex("dbo.WorkSiteWorkSiteType", new[] { "WorkSite_Id" });
            DropPrimaryKey("dbo.EmployerInfoes");
            DropPrimaryKey("dbo.WorkerCountInfoes");
            DropPrimaryKey("dbo.Addresses");
            DropPrimaryKey("dbo.HourlyWageInfoes");
            DropPrimaryKey("dbo.PrevailingWageSurveyInfoes");
            DropPrimaryKey("dbo.SourceEmployers");
            DropPrimaryKey("dbo.PieceRateWageInfoes");
            DropPrimaryKey("dbo.WIOAs");
            DropPrimaryKey("dbo.WIOAWorkers");
            DropPrimaryKey("dbo.WorkSites");
            DropPrimaryKey("dbo.Employees");
            DropPrimaryKey("dbo.WorkSiteWorkSiteType");
            DropColumn("dbo.ApplicationSubmissions", "Employer_Id");
            DropColumn("dbo.ApplicationSubmissions", "HourlyWageInfo_Id");
            DropColumn("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id");
            DropColumn("dbo.ApplicationSubmissions", "WIOA_Id");
            DropColumn("dbo.EmployerInfoes", "Id");
            DropColumn("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id");
            DropColumn("dbo.EmployerInfoes", "ParentAddress_Id");
            DropColumn("dbo.EmployerInfoes", "PhysicalAddress_Id");
            DropColumn("dbo.WorkerCountInfoes", "Id");
            DropColumn("dbo.Addresses", "Id");
            DropColumn("dbo.HourlyWageInfoes", "Id");
            DropColumn("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            DropColumn("dbo.PrevailingWageSurveyInfoes", "Id");
            DropColumn("dbo.SourceEmployers", "Id");
            DropColumn("dbo.SourceEmployers", "Address_Id");
            DropColumn("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id");
            DropColumn("dbo.PieceRateWageInfoes", "Id");
            DropColumn("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            DropColumn("dbo.WIOAs", "Id");
            DropColumn("dbo.WIOAWorkers", "Id");
            DropColumn("dbo.WIOAWorkers", "WIOA_Id");
            DropColumn("dbo.WorkSites", "Id");
            DropColumn("dbo.WorkSites", "Address_Id");
            DropColumn("dbo.Employees", "Id");
            DropColumn("dbo.Employees", "WorkSite_Id");
            DropColumn("dbo.WorkSiteWorkSiteType", "WorkSite_Id");
            AddColumn("dbo.ApplicationSubmissions", "Employer_Id", c => c.Guid(nullable: false));
            AddColumn("dbo.ApplicationSubmissions", "HourlyWageInfo_Id", c => c.Guid());
            AddColumn("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id", c => c.Guid());
            AddColumn("dbo.ApplicationSubmissions", "WIOA_Id", c => c.Guid(nullable: false));
            AddColumn("dbo.EmployerInfoes", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id", c => c.Guid(nullable: false));
            AddColumn("dbo.EmployerInfoes", "ParentAddress_Id", c => c.Guid());
            AddColumn("dbo.EmployerInfoes", "PhysicalAddress_Id", c => c.Guid(nullable: false));
            AddColumn("dbo.WorkerCountInfoes", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.Addresses", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.HourlyWageInfoes", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id", c => c.Guid());
            AddColumn("dbo.PrevailingWageSurveyInfoes", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.SourceEmployers", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.SourceEmployers", "Address_Id", c => c.Guid(nullable: false));
            AddColumn("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id", c => c.Guid());
            AddColumn("dbo.PieceRateWageInfoes", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id", c => c.Guid());
            AddColumn("dbo.WIOAs", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.WIOAWorkers", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.WIOAWorkers", "WIOA_Id", c => c.Guid());
            AddColumn("dbo.WorkSites", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.WorkSites", "Address_Id", c => c.Guid(nullable: false));
            AddColumn("dbo.Employees", "Id", c => c.Guid(nullable: false));
            AddColumn("dbo.Employees", "WorkSite_Id", c => c.Guid());
            AddColumn("dbo.WorkSiteWorkSiteType", "WorkSite_Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.EmployerInfoes", "Id");
            AddPrimaryKey("dbo.WorkerCountInfoes", "Id");
            AddPrimaryKey("dbo.Addresses", "Id");
            AddPrimaryKey("dbo.HourlyWageInfoes", "Id");
            AddPrimaryKey("dbo.PrevailingWageSurveyInfoes", "Id");
            AddPrimaryKey("dbo.SourceEmployers", "Id");
            AddPrimaryKey("dbo.PieceRateWageInfoes", "Id");
            AddPrimaryKey("dbo.WIOAs", "Id");
            AddPrimaryKey("dbo.WIOAWorkers", "Id");
            AddPrimaryKey("dbo.WorkSites", "Id");
            AddPrimaryKey("dbo.Employees", "Id");
            AddPrimaryKey("dbo.WorkSiteWorkSiteType", new[] { "WorkSite_Id", "Response_Id" });
            CreateIndex("dbo.ApplicationSubmissions", "Employer_Id");
            CreateIndex("dbo.ApplicationSubmissions", "HourlyWageInfo_Id");
            CreateIndex("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id");
            CreateIndex("dbo.ApplicationSubmissions", "WIOA_Id");
            CreateIndex("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id");
            CreateIndex("dbo.EmployerInfoes", "ParentAddress_Id");
            CreateIndex("dbo.EmployerInfoes", "PhysicalAddress_Id");
            CreateIndex("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            CreateIndex("dbo.SourceEmployers", "Address_Id");
            CreateIndex("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id");
            CreateIndex("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            CreateIndex("dbo.WIOAWorkers", "WIOA_Id");
            CreateIndex("dbo.WorkSites", "Address_Id");
            CreateIndex("dbo.Employees", "WorkSite_Id");
            CreateIndex("dbo.WorkSiteWorkSiteType", "WorkSite_Id");
            AddForeignKey("dbo.ApplicationSubmissions", "Employer_Id", "dbo.EmployerInfoes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id", "dbo.WorkerCountInfoes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmployerInfoes", "ParentAddress_Id", "dbo.Addresses", "Id");
            AddForeignKey("dbo.EmployerInfoes", "PhysicalAddress_Id", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SourceEmployers", "Address_Id", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.WorkSites", "Address_Id", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ApplicationSubmissions", "HourlyWageInfo_Id", "dbo.HourlyWageInfoes", "Id");
            AddForeignKey("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id", "dbo.PrevailingWageSurveyInfoes", "Id");
            AddForeignKey("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes", "Id");
            AddForeignKey("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes", "Id");
            AddForeignKey("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id", "dbo.PieceRateWageInfoes", "Id");
            AddForeignKey("dbo.WIOAWorkers", "WIOA_Id", "dbo.WIOAs", "Id");
            AddForeignKey("dbo.ApplicationSubmissions", "WIOA_Id", "dbo.WIOAs", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "WorkSite_Id", "dbo.WorkSites", "Id");
            AddForeignKey("dbo.WorkSiteWorkSiteType", "WorkSite_Id", "dbo.WorkSites", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.WorkSiteWorkSiteType", "WorkSite_Id", "dbo.WorkSites");
            DropForeignKey("dbo.Employees", "WorkSite_Id", "dbo.WorkSites");
            DropForeignKey("dbo.ApplicationSubmissions", "WIOA_Id", "dbo.WIOAs");
            DropForeignKey("dbo.WIOAWorkers", "WIOA_Id", "dbo.WIOAs");
            DropForeignKey("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id", "dbo.PieceRateWageInfoes");
            DropForeignKey("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes");
            DropForeignKey("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes");
            DropForeignKey("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id", "dbo.PrevailingWageSurveyInfoes");
            DropForeignKey("dbo.ApplicationSubmissions", "HourlyWageInfo_Id", "dbo.HourlyWageInfoes");
            DropForeignKey("dbo.WorkSites", "Address_Id", "dbo.Addresses");
            DropForeignKey("dbo.SourceEmployers", "Address_Id", "dbo.Addresses");
            DropForeignKey("dbo.EmployerInfoes", "PhysicalAddress_Id", "dbo.Addresses");
            DropForeignKey("dbo.EmployerInfoes", "ParentAddress_Id", "dbo.Addresses");
            DropForeignKey("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id", "dbo.WorkerCountInfoes");
            DropForeignKey("dbo.ApplicationSubmissions", "Employer_Id", "dbo.EmployerInfoes");
            DropIndex("dbo.WorkSiteWorkSiteType", new[] { "WorkSite_Id" });
            DropIndex("dbo.Employees", new[] { "WorkSite_Id" });
            DropIndex("dbo.WorkSites", new[] { "Address_Id" });
            DropIndex("dbo.WIOAWorkers", new[] { "WIOA_Id" });
            DropIndex("dbo.PieceRateWageInfoes", new[] { "MostRecentPrevailingWageSurvey_Id" });
            DropIndex("dbo.SourceEmployers", new[] { "PrevailingWageSurveyInfo_Id" });
            DropIndex("dbo.SourceEmployers", new[] { "Address_Id" });
            DropIndex("dbo.HourlyWageInfoes", new[] { "MostRecentPrevailingWageSurvey_Id" });
            DropIndex("dbo.EmployerInfoes", new[] { "PhysicalAddress_Id" });
            DropIndex("dbo.EmployerInfoes", new[] { "ParentAddress_Id" });
            DropIndex("dbo.EmployerInfoes", new[] { "NumSubminimalWageWorkers_Id" });
            DropIndex("dbo.ApplicationSubmissions", new[] { "WIOA_Id" });
            DropIndex("dbo.ApplicationSubmissions", new[] { "PieceRateWageInfo_Id" });
            DropIndex("dbo.ApplicationSubmissions", new[] { "HourlyWageInfo_Id" });
            DropIndex("dbo.ApplicationSubmissions", new[] { "Employer_Id" });
            DropPrimaryKey("dbo.WorkSiteWorkSiteType");
            DropPrimaryKey("dbo.Employees");
            DropPrimaryKey("dbo.WorkSites");
            DropPrimaryKey("dbo.WIOAWorkers");
            DropPrimaryKey("dbo.WIOAs");
            DropPrimaryKey("dbo.PieceRateWageInfoes");
            DropPrimaryKey("dbo.SourceEmployers");
            DropPrimaryKey("dbo.PrevailingWageSurveyInfoes");
            DropPrimaryKey("dbo.HourlyWageInfoes");
            DropPrimaryKey("dbo.Addresses");
            DropPrimaryKey("dbo.WorkerCountInfoes");
            DropPrimaryKey("dbo.EmployerInfoes");
            DropColumn("dbo.WorkSiteWorkSiteType", "WorkSite_Id");
            DropColumn("dbo.Employees", "WorkSite_Id");
            DropColumn("dbo.Employees", "Id");
            DropColumn("dbo.WorkSites", "Address_Id");
            DropColumn("dbo.WorkSites", "Id");
            DropColumn("dbo.WIOAWorkers", "WIOA_Id");
            DropColumn("dbo.WIOAWorkers", "Id");
            DropColumn("dbo.WIOAs", "Id");
            DropColumn("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            DropColumn("dbo.PieceRateWageInfoes", "Id");
            DropColumn("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id");
            DropColumn("dbo.SourceEmployers", "Address_Id");
            DropColumn("dbo.SourceEmployers", "Id");
            DropColumn("dbo.PrevailingWageSurveyInfoes", "Id");
            DropColumn("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            DropColumn("dbo.HourlyWageInfoes", "Id");
            DropColumn("dbo.Addresses", "Id");
            DropColumn("dbo.WorkerCountInfoes", "Id");
            DropColumn("dbo.EmployerInfoes", "PhysicalAddress_Id");
            DropColumn("dbo.EmployerInfoes", "ParentAddress_Id");
            DropColumn("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id");
            DropColumn("dbo.EmployerInfoes", "Id");
            DropColumn("dbo.ApplicationSubmissions", "WIOA_Id");
            DropColumn("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id");
            DropColumn("dbo.ApplicationSubmissions", "HourlyWageInfo_Id");
            DropColumn("dbo.ApplicationSubmissions", "Employer_Id");
            AddColumn("dbo.WorkSiteWorkSiteType", "WorkSite_Id", c => c.Int(nullable: false));
            AddColumn("dbo.Employees", "WorkSite_Id", c => c.Int());
            AddColumn("dbo.Employees", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.WorkSites", "Address_Id", c => c.Int(nullable: false));
            AddColumn("dbo.WorkSites", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.WIOAWorkers", "WIOA_Id", c => c.Int());
            AddColumn("dbo.WIOAWorkers", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.WIOAs", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id", c => c.Int());
            AddColumn("dbo.PieceRateWageInfoes", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id", c => c.Int());
            AddColumn("dbo.SourceEmployers", "Address_Id", c => c.Int(nullable: false));
            AddColumn("dbo.SourceEmployers", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.PrevailingWageSurveyInfoes", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id", c => c.Int());
            AddColumn("dbo.HourlyWageInfoes", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Addresses", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.WorkerCountInfoes", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.EmployerInfoes", "PhysicalAddress_Id", c => c.Int(nullable: false));
            AddColumn("dbo.EmployerInfoes", "ParentAddress_Id", c => c.Int());
            AddColumn("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id", c => c.Int(nullable: false));
            AddColumn("dbo.EmployerInfoes", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.ApplicationSubmissions", "WIOA_Id", c => c.Int(nullable: false));
            AddColumn("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id", c => c.Int());
            AddColumn("dbo.ApplicationSubmissions", "HourlyWageInfo_Id", c => c.Int());
            AddColumn("dbo.ApplicationSubmissions", "Employer_Id", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.WorkSiteWorkSiteType", new[] { "WorkSite_Id", "Response_Id" });
            AddPrimaryKey("dbo.Employees", "Id");
            AddPrimaryKey("dbo.WorkSites", "Id");
            AddPrimaryKey("dbo.WIOAWorkers", "Id");
            AddPrimaryKey("dbo.WIOAs", "Id");
            AddPrimaryKey("dbo.PieceRateWageInfoes", "Id");
            AddPrimaryKey("dbo.SourceEmployers", "Id");
            AddPrimaryKey("dbo.PrevailingWageSurveyInfoes", "Id");
            AddPrimaryKey("dbo.HourlyWageInfoes", "Id");
            AddPrimaryKey("dbo.Addresses", "Id");
            AddPrimaryKey("dbo.WorkerCountInfoes", "Id");
            AddPrimaryKey("dbo.EmployerInfoes", "Id");
            CreateIndex("dbo.WorkSiteWorkSiteType", "WorkSite_Id");
            CreateIndex("dbo.Employees", "WorkSite_Id");
            CreateIndex("dbo.WorkSites", "Address_Id");
            CreateIndex("dbo.WIOAWorkers", "WIOA_Id");
            CreateIndex("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            CreateIndex("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id");
            CreateIndex("dbo.SourceEmployers", "Address_Id");
            CreateIndex("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id");
            CreateIndex("dbo.EmployerInfoes", "PhysicalAddress_Id");
            CreateIndex("dbo.EmployerInfoes", "ParentAddress_Id");
            CreateIndex("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id");
            CreateIndex("dbo.ApplicationSubmissions", "WIOA_Id");
            CreateIndex("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id");
            CreateIndex("dbo.ApplicationSubmissions", "HourlyWageInfo_Id");
            CreateIndex("dbo.ApplicationSubmissions", "Employer_Id");
            AddForeignKey("dbo.WorkSiteWorkSiteType", "WorkSite_Id", "dbo.WorkSites", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "WorkSite_Id", "dbo.WorkSites", "Id");
            AddForeignKey("dbo.ApplicationSubmissions", "WIOA_Id", "dbo.WIOAs", "Id", cascadeDelete: true);
            AddForeignKey("dbo.WIOAWorkers", "WIOA_Id", "dbo.WIOAs", "Id");
            AddForeignKey("dbo.ApplicationSubmissions", "PieceRateWageInfo_Id", "dbo.PieceRateWageInfoes", "Id");
            AddForeignKey("dbo.PieceRateWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes", "Id");
            AddForeignKey("dbo.HourlyWageInfoes", "MostRecentPrevailingWageSurvey_Id", "dbo.PrevailingWageSurveyInfoes", "Id");
            AddForeignKey("dbo.SourceEmployers", "PrevailingWageSurveyInfo_Id", "dbo.PrevailingWageSurveyInfoes", "Id");
            AddForeignKey("dbo.ApplicationSubmissions", "HourlyWageInfo_Id", "dbo.HourlyWageInfoes", "Id");
            AddForeignKey("dbo.WorkSites", "Address_Id", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SourceEmployers", "Address_Id", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmployerInfoes", "PhysicalAddress_Id", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EmployerInfoes", "ParentAddress_Id", "dbo.Addresses", "Id");
            AddForeignKey("dbo.EmployerInfoes", "NumSubminimalWageWorkers_Id", "dbo.WorkerCountInfoes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ApplicationSubmissions", "Employer_Id", "dbo.EmployerInfoes", "Id", cascadeDelete: true);
        }
    }
}
